# Generated by Django 6.0 on 2026-01-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialtime',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='trialtime',
            name='vehicle',
            field=models.ManyToManyField(to='base.vehicle'),
        ),
    ]
