# Generated by Django 6.0 on 2026-01-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_trialtime_vehicle_trialtime_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='trialtime',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.timeslot'),
        ),
    ]
