# Generated by Django 6.0 on 2026-01-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_timeslot_alter_trialtime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialtime',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='trialtime',
            name='vehicle',
            field=models.ForeignKey(default=333, on_delete=django.db.models.deletion.CASCADE, to='base.vehicle'),
            preserve_default=False,
        ),
    ]
