# Generated by Django 6.0 on 2026-01-06 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_trialtime_vehicle_trialtime_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trial_time',
            field=models.ForeignKey(default=333, on_delete=django.db.models.deletion.CASCADE, to='base.trialtime'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('vehicle', 'trial_time'), name='unique_vehicle_trial_time'),
        ),
    ]
