# Generated by Django 6.0 on 2026-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_booking_trial_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_vehicle_trial_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('vehicle', 'trial_time')},
        ),
    ]
