# Generated by Django 6.0 on 2026-01-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_booking_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trialtime',
            unique_together={('vehicle', 'time')},
        ),
    ]
