# Generated by Django 6.0 on 2026-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_booking_options_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
